### ISSUE TITLE
Parsing Bug When Using CoqHammer 1.3

### ISSUE THREAD

**Issue by yalhessi** [lukaszcz/coqhammer#106]
Coq version: Tested on 8.10, 8.11, possibly applicable to more 
CoqHammer version: 1.3, not an issue on 1.2.1 (from Opam)
Operating System: Ubuntu 18.04.4
Interface: Coqtop, CoqIDE

@HazardousPeach and I use CoqHammer as part of our [Coq theorem prover](https://github.com/UCSD-PL/proverbot9001). We noticed after upgrading to hammer 1.3 we run into parsing errors. 

Example:
**Coq < From Hammer Require Import Hammer.**
**Coq < Lemma nat_eq (p q: nat): {p = q} + {p <> q}.**
Toplevel input, characters 16-18:
> Lemma nat_eq (p q: nat): {p = q} + {p <> q}.
>_______________^^
Error:
Syntax error: ':=' or ':' or [Prim.name] expected after [Prim.name] (in [constr:closed_binder]).

This issue seems to only be present in 1.3. The bug It also appears to be magically tied to having the characters `q` and `:` appear sequentially without a space separating them. The lemma definition parses successfully if there's a space between the two characters. It also parses if hammer is not imported.

**Comment by HazardousPeach** [comment]
Note that it also parses if you use an identifier **besides** "q", like "a". I've also had this problem on 1.2.1 for Coq 8.10.2, but not 1.2.1 for Coq 8.11.0

**Comment by lukaszcz** [comment]
Thank you for the report. This seems to be related to the fact that q:
indicates an sauto option. I'll look into it.

**Comment by lukaszcz** [comment]
Fixed with commit ac353799fb7176efa99fc18a5cffab5de774661a
