### ISSUE TITLE
Extending hammer/sauto to use induction?

### ISSUE THREAD

**Issue by brando90** [lukaszcz/coqhammer#125]
I was curious, what would it take to have hammer & sauto be as automatic as possible? e.g. doing things like induction by itself properly. Perhaps failing if the time limit is failed.

**Comment by lukaszcz** [comment]
Doing induction in a "stupid" way isn't difficult - just exhaustively try induction on anything you can that is in the context. But this would increase the search space. Doing induction properly requires something like the rippling heuristic which I'm not going to implement (myself) for lack of time.

**Comment by brando90** [comment]
Hi Lukasz,

Thanks for the response. Do you have 

1. a reference for how to implement such a heuristic search algorithm
2. do you have a guess of how long/effort it would take to implement it?
3. if implemented would it be in ltac2 or ocaml (as a plugin)?

thanks for your time it's appreciated.

Regards, Brando

**Comment by lukaszcz** [comment]
>
> 1. a reference for how to implement such a heuristic search algorithm

 Google: rippling induction

See also: https://github.com/tomprince/rippling,
https://coq.discourse.group/t/inductive-proof-automation/226,
https://hal.archives-ouvertes.fr/inria-00489496/en/

>
> 2. do you have a guess of how long/effort it would take to implement it?

I don't know, but it's not trivial. Could be a topic for an MSc or
even a PhD thesis.

> 3. if implemented would it be in ltac2 or ocaml (as a plugin)?

However one wants to do it, but some ocaml plugin programming would be
needed to connect it to existing code at the very least. And I'm not
sure about how usable ltac2 is for general-purpose programming -
haven't tried it yet.
