### ISSUE TITLE
Why does hammer try to call smt solvers when I use it? I thought it didn't

### ISSUE THREAD

**Issue by brando90** [lukaszcz/coqhammer#126]
```
Error: Error running cvc4.
Error: Error running cvc4.
Error: Error running vampire.
Error: Error running vampire.
Error: Error running z3_tptp.
Error: Error running cvc4.
Error: Error running cvc4.
Error: Error running cvc4.
Error: Error running cvc4.
Error: Error running vampire.
Error: Error running vampire.
Error: Error running cvc4.
Error: Error running z3_tptp.
Error: Error running cvc4
```

what does this error mean when I run hammer? I thought hammer was suppose to not use SMT solver so this confuses me.

**Comment by lukaszcz** [comment]
??? Why shouldn't it use them? It uses them as ATPs.

I don't know what the error means without more context. Probably the provers are not configured properly.

**Comment by brando90** [comment]
didn't you recommend somewhere to use SMTCoq?  That is why I thought your tool didn't use SMT solvers...or did I get confused?

**Comment by lukaszcz** [comment]
Coqhammer uses smt solvers differently than SMTCoq. It pretends they are
general ATPs and does use any specific smt theories. So e.g. arithmetic
goals won't be translated to use smt integers with Coqhammer, in contrast
to SMTCoq

**Comment by lukaszcz** [comment]
does *not* use any specific smt theories
