### ISSUE TITLE
how to provide lemma to hammer (not sauto)?

### ISSUE THREAD

**Issue by brando90** [lukaszcz/coqhammer#127]
I know hammer is meant mostly to find dependencies using classical atps -- but I was curious if it was possible to provide hammer extra lemmas directly if we want them. e.g. doing `hammer use: LEMMA1.`
Or perhaps the only way to do it is to define a lemma externally first or with a `have: .... by proof` statement first then run hammer in the next proof?

**Comment by lukaszcz** [comment]
Yes, "hammer" will use anything that's in the context. You can add things to the context also with the "use" tactic. "hammer" doesn't accept any options.

**Comment by brando90** [comment]
assert and have: also add things to the context afaik. No? funny there are 3 things for that use, have, assert in Coq...

**Comment by lukaszcz** [comment]
"use" is a tactic from CoqHammer which also simplifies the added hypotheses
