### ISSUE TITLE
Why does hammer get confused when trying to find proofs for subgoals?

### ISSUE THREAD

**Issue by brando90** [lukaszcz/coqhammer#128]
I found this surprising when I was watching the hammer tutorial. Since to me the most useful part of hammer is likely to use the intuition a human has to apply tactic, break goals, create helper lemmas, **call intuition properly** and then have hammer do the "easy parts". Sort of a divide and conquer together. 

Why is this not possible? It seems like a really useful feature for hammer to work with subgoals.

**Comment by lukaszcz** [comment]
It doesn't necessarily get confused. It's just you typically have more clutter in subgoals, unnecessary hypotheses, spurious specialisation of the goal you want to prove. Abstracting this into a lemma often removes the clutter and makes "hammer" more effective.

**Comment by brando90** [comment]
apologies, I'm confused. Does hammer still work in subgoals or not? That's what I'm worried.

Thanks for your replies! :)

**Comment by lukaszcz** [comment]
It does, in general (unless you have existential metavariables, but that's
a different issue). It just mightbe less effective when there is clutter.
