### ISSUE TITLE
New release or version 1.1 for Coq 8.9 in OPAM?

### ISSUE THREAD

**Issue by palmskog** [lukaszcz/coqhammer#16]
Thanks to our earlier compatibility efforts, [release 1.1](https://github.com/lukaszcz/coqhammer/releases/tag/v1.1-coq8.8) appears to work fine with the newly released Coq 8.9.0.

However, the version name (`1.1+8.8`) and version string (`CoqHammer 1.1 for Coq 8.8 and Coq 8.9beta`) may be misleading. So, should I modify the existing OPAM package for 8.9 compatibility, or do you want to make a new release (and have a new OPAM package)?

**Comment by lukaszcz** [comment]
I'll make a new version.

**Comment by lukaszcz** [comment]
The new version is in the v1.1-coq8.9 branch.
