### ISSUE TITLE
Separate packaging of tactics and plugin?

### ISSUE THREAD

**Issue by palmskog** [lukaszcz/coqhammer#17]
We have been using CoqHammer extensively to translate proofs at the "specification level" from Isabelle/HOL to Coq (see [project](https://github.com/runtimeverification/casper-proofs) and CoqPL [materials](https://popl19.sigplan.org/event/coqpl-2019-verifying-finality-for-blockchain-systems)). I think this worked really well, echoing Paulson's [experience](https://arxiv.org/abs/1804.07860) going from HOL Light to Isabelle/HOL, and is an application area that should be highlighted.

However, once we were done hammering, it appeared unnecessary to still have the whole CoqHammer plugin as a requirement for the project, when all we really needed were a few of the CoqHammer standalone tactics. Isabelle doesn't have this problem, since all hammer "replacement tactics", such as `metis`, are built-in.

Would it make sense to have separate packages (and thus build scripts) for CoqHammer's tactics and the CoqHammer plugin? Would a PR to implement this be welcome?

**Comment by lukaszcz** [comment]
Currently, all tactics are in the "theories/Reconstr.v" file, which is
independent of the rest of the plugin. The file may be used without the
plugin installed. Though this may change in future versions.

**Comment by palmskog** [comment]
> Currently, all tactics are in the "theories/Reconstr.v" file, which is independent of the rest of the plugin. The file may be used without the plugin installed.

Right, but there's no build task in `Makefile` that builds/installs only `theories/Reconstr.v`. If there was something like that, I could easily factor the OPAM package into `coq-hammer` and `coq-hammer-tactics`, where the former is a requirement of the latter.

**Comment by lukaszcz** [comment]
Right now, it is not much of an issue to just copy the "Reconstr.v" file,
but a separate package may be nonetheless useful, especially in the future.

**Comment by lukaszcz** [comment]
Added install-tactics target
