### ISSUE TITLE
[warnings] Please fix OCaml warnings

### ISSUE THREAD

**Issue by ejgallego** [lukaszcz/coqhammer#18]
Dear devs,

in Coq we are considering requiring plugins in the CI to use the same set of compiler flags for warnings than the main Coq tree (c.f. https://github.com/coq/coq/pull/9605 ), in particular, this means that the plugins should now compile warning-free, except for deprecation notices.

Note that some of the raised warnings are really fatal, [like missing match cases].

Please, try to fix OCaml warnings present in your codebase, thanks!

**Comment by lukaszcz** [comment]
Fixed with the latest commit.

**Comment by ejgallego** [comment]
Thanks a lot!
