### ISSUE TITLE
Release with CVC4 support

### ISSUE THREAD

**Issue by palmskog** [lukaszcz/coqhammer#3]
Would be great with a proper GitHub release with support for CVC4 that can be included in Coq's OPAM. I can also confirm that current master works with the newly released Coq 8.8.2.

**Comment by lukaszcz** [comment]
Yes, I think I'll do this sometime soon, but there is one bug I wanted to
fix before making a new release.

**Comment by lukaszcz** [comment]
Release 1.1 done.
