### ISSUE TITLE
Release with tactics/plugin package split and quick plugin and tactics tests

### ISSUE THREAD

**Issue by palmskog** [lukaszcz/coqhammer#33]
Thanks for merging the changes for separate tactics and plugin packages - this will be a big improvement for the projects I'm using CoqHammer in. On that note, do you think it's worth applying these changes to the `coq8.9` branch also? If so, I can do a PR for that, but then I think there should be a new release based on that branch as well.

**Comment by lukaszcz** [comment]
Yes, I think it's worth it. There are also some small CoqHammer improvements in the coq8.9 branch I haven't merged yet to other branches. I'll make a new release afterwards.

**Comment by lukaszcz** [comment]
I created basic "quick tests" which do not require the installation of external ATPs. `make test-plugin` tests the plugin (but not the tactics), and `make test-tactics` tests the tactics (plugin need not be installed). `make quicktest` invokes both. @palmskog could you incorporate this into opam/travis?

**Comment by palmskog** [comment]
Sure, let's start with `master` first though and move from there.

**Comment by lukaszcz** [comment]
These recent changes are already in master, coq8.10, and coq8.9 branches.

**Comment by palmskog** [comment]
Sure, but I'll make a PR for `master` first, and if things work well there, I'll move on to the others.

**Comment by lukaszcz** [comment]
I made the 1.1.1 release.

**Comment by palmskog** [comment]
According to my local tests, the release seems to work fine on Coq 8.8.2. Should I still call the release `1.1.1+8.9` in OPAM but allow installs with Coq 8.8? Or maybe just `1.1.1`?

**Comment by palmskog** [comment]
Never mind, I went with the previous convention. There is now also a small [blurb](https://coq.discourse.group/t/coqhammer-1-1-1-for-coq-8-9/327) in the Coq Discourse forum.
