### ISSUE TITLE
Coq's CI

### ISSUE THREAD

**Issue by ejgallego** [lukaszcz/coqhammer#4]
Hi @lukaszcz , would you be interested in adding `coqhammer` to Coq's CI?

See https://github.com/coq/coq/blob/master/dev/ci/README.md#information-for-external-library--plugin-authors

Let us know if you have any question.

**Comment by lukaszcz** [comment]
I added CoqHammer CI as described in dev/ci/README.md and made a pull request.

**Comment by ejgallego** [comment]
Cool thanks!

**Comment by ejgallego** [comment]
Coq's PR https://github.com/coq/coq/pull/8976

**Comment by lukaszcz** [comment]
Apparently, the Coq team is not happy with my commit, and wants CI to be set up on CoqHammer side (whatever this means), which requires playing with docker and some other stuff I don't know. @ekiciburak Burak, could you see to this in the near future? I won't have time to work on this soon.

**Comment by ejgallego** [comment]
The commit is fine, just a rename is needed so the project name is `ci-coqhammer` same as this repos.

I can setup the travis file, that should be trivial.

**Comment by lukaszcz** [comment]
OK, thanks. I'll just change the name then.

**Comment by ejgallego** [comment]
Indeed be aware that once you add CoqHammer to Coq's CI you should be careful to keep your master branch in a working state, thus the recommendation for CI.

**Comment by ejgallego** [comment]
What is gonna be your branch policy?

In Coq we recommend having a branch for each Coq branch, that is to say v8.9, and `master`, Coq's future 8.10.
