### ISSUE TITLE
Release for Coq 8.10?

### ISSUE THREAD

**Issue by palmskog** [lukaszcz/coqhammer#44]
I believe the `coq8.10` branch is ready for a release that officially supports the recently-released Coq 8.10.0. While the Coq OPAM package is currently stuck as a pull request, I can submit new CoqHammer OPAM packages for a new release as soon as the Coq package is out.

**Comment by lukaszcz** [comment]
I made the v1.1.1-coq8.10 branch.

**Comment by palmskog** [comment]
The `8.10.0` OPAM package for Coq is finally out, and I've tested it with the `v1.1.1-coq8.10` branch. Any chance for a GitHub release of the branch that I can package?

**Comment by lukaszcz** [comment]
The v1.1.1-coq8.10 branch is a packageable branch, containing the 1.1.1
version adapted to Coq 8.10.

**Comment by lukaszcz** [comment]
I'll make a release

**Comment by palmskog** [comment]
Thanks, we impose the restriction that only tarballs/archives can be packaged in the usual (`released`) Coq OPAM repo (and not repo branches), that's why I ask for a GitHub release.
