### ISSUE TITLE
Deprecation of Pervasives module in OCaml > 4.07

### ISSUE THREAD

**Issue by palmskog** [lukaszcz/coqhammer#45]
Recent versions of OCaml (> 4.07) have deprecated the module `Pervasives` in favor of `Stdlib`. This means that CoqHammer currently shows deprecation warnings like the following when compiled with, e.g., OCaml 4.09.0:
```
File "src/coq_transl.ml", line 1141, characters 30-48:
1141 |   Hhlib.sort_uniq (fun x y -> Pervasives.compare (fst x) (fst y)) axs
                                     ^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
```
Since Coq users are in my experience slow to migrate to new OCaml compilers, making [stdlib-shims](https://github.com/ocaml/stdlib-shims) a dependency may be the best solution. However, note that these deprecations are not urgent to address as of right now.

**Comment by lukaszcz** [comment]
Fixed with b0ed2eeb4664bbe97b16540dfde03b6dd96a48c3
