### ISSUE TITLE
Release for Coq 8.11?

### ISSUE THREAD

**Issue by palmskog** [lukaszcz/coqhammer#51]
Since Coq 8.11.0 is now out, any chance of a release (with a GitHub tarball) of CoqHammer that is compatible with that version? As before, I can take care of submitting an OPAM package for the Coq OPAM archive.

**Comment by lukaszcz** [comment]
I'll make a new major release for Coq 8.10 and 8.11 in a week or two. This release will include improvements to the reconstruction tactics, with a new proof search procedure.

**Comment by lukaszcz** [comment]
Finally done.
