### ISSUE TITLE
Use coqhammer for a user changed coq

### ISSUE THREAD

**Issue by Zhang-Liao** [lukaszcz/coqhammer#53]
Dear designer of coqhammer, 

I make some changes to the coq source code and then want to use coqhammer in my changed coq. I have got the directory _Hammer_ which contains necessary files for coqhammer in the opam directory.
Then I add the directory _Hammer_ in coq's source. What should I do so that I can use tactic from coqhammer in my coq version?

**Comment by lukaszcz** [comment]
Build CoqHammer from source using "make", following the instructions in README.md, like with any other non-opam-installed version of Coq.

**Comment by Zhang-Liao** [comment]
> Build CoqHammer from source using "make", following the instructions in README.md, like with any other non-opam-installed version of Coq.
Very sorry to trouble you. I still have one question. After I build CoqHammer from source, where should I put it? Should I put in the source directory of my coq? Like in the opam, in the _user-contrib_ directory of coq? And how should I use coq hammer in my coq? Still use _From Hammer require import Hammer_. Much appreciation to you!

**Comment by Zhang-Liao** [comment]
> Build CoqHammer from source using "make", following the instructions in README.md, like with any other non-opam-installed version of Coq.

After changing, I hope I can use CoqHammer in CoqIde using my coq

**Comment by lukaszcz** [comment]
CoqHammer's "make install" installs to an appropriate user-contrib directory for your currently installed Coq (available via the coqtop command), or you can use the COQBIN variable. Coqide will work with CoqHammer if the version of Coq it uses is the one for which CoqHammer was installed. Please learn how to install Coq from source and how to install Coq plugins (search the Internet).
