### ISSUE TITLE
Hosting historical CoqHammer archives on GitHub

### ISSUE THREAD

**Issue by palmskog** [lukaszcz/coqhammer#58]
Coq OPAM archive maintainers recently noticed that the CoqHammer website (http://cl-informatik.uibk.ac.at/cek/coqhammer/) went down, possibly due to some reorganization at the hosting university.

This has left several files with early versions of CoqHammer unavailable. Even if the website comes back up eventually, would it be possible to host these files on GitHub for preservation purposes? For example, future research may do some comparison of hammers across versions.

Some examples of (former URLs of) unavailable files:
http://cl-informatik.uibk.ac.at/cek/coqhammer/coqhammer-1.0.3-coq8.6.tar.gz
http://cl-informatik.uibk.ac.at/cek/coqhammer/coqhammer-1.0.6-coq8.6.tar.gz
http://cl-informatik.uibk.ac.at/cek/coqhammer/coqhammer-0.9-coq8.5.tar.gz
http://cl-informatik.uibk.ac.at/cek/coqhammer/atp-experiments.tgz

Here is an example of what a "historical" release can look like on GitHub: https://github.com/math-comp/math-comp/releases/tag/archive - basically, the idea is to use GitHub's feature to associate a release with a manually uploaded file.

**Comment by cezaryka** [comment]
On Sat, Feb 29, 2020 at 5:08 PM Karl Palmskog <notifications@github.com> wrote:
> Coq OPAM archive maintainers recently noticed that the CoqHammer website (http://cl-informatik.uibk.ac.at/cek/coqhammer/) went down, possibly due to some reorganization at the hosting university.

FYI: It was a temporary server failure of whole computer science
department in Innsbruck. The web servers are back online and there is
currently no plan for reorganization.

Regards,
Cezary

-- 
Cezary Kaliszyk, University of Innsbruck,
http://cl-informatik.uibk.ac.at/~cek/

**Comment by lukaszcz** [comment]
I don't think there is a need to do this now. That was a temporary failure and I'm sure Cezary will let me know if the Innsbruck website is ever going to become permanently unavailable.
