### ISSUE TITLE
Is it able to set the number of predicted premises returned by tactic "predict"?

### ISSUE THREAD

**Issue by Zhang-Liao** [lukaszcz/coqhammer#60]
Sorry to trouble you. Sometimes I think the tactic `predict` returns too many premises which costs too much time. Is it possible to do some change to the code to limit the number of the premises returned? It seems can not be changed by some constants in the tactics like `predict 500`. If it is possible, which file should I change?

**Comment by lukaszcz** [comment]
Probably fixed with https://github.com/lukaszcz/coqhammer/pull/61. Please reopen if this doesn't solve your issue ("predict n" should print n predictions).
