### ISSUE TITLE
Failing hammer tactic causes Coq anomaly in Coq 8.11

### ISSUE THREAD

**Issue by palmskog** [lukaszcz/coqhammer#70]
When the `hammer` tactic in CoqHammer 1.2 for Coq 8.11 fails, it also reports an anomaly, as follows:
```
Error: Hammer failed: ATPs failed to find a proof
Error: Anomaly "Uncaught exception Failure("Hammer failed")." Please report at http://coq.inria.fr/bugs/.
```
This can be misleading to the user, since the "problem" is not in Coq and should not be reported as a bug. According to the Coq developers, the recommended way of handling exceptions (instead of leaving them uncaught) is to use `CErrors.user_err`.

**Comment by lukaszcz** [comment]
This has already been fixed in the default development branch (coq8.11)

**Comment by palmskog** [comment]
I see, feel free to close this issue then. But may I suggest a small release incremental release in the near future to address this (`1.2.1+8.11`)? Otherwise, either this project or Coq itself may get more issue reports...

**Comment by lukaszcz** [comment]
Yes, I can do it relatively quickly. The problem was I used a wrong (too
primitive) tactic for failing in the ocaml plugin.

**Comment by lukaszcz** [comment]
The v. 1.2.1 release for Coq 8.10 and 8.11 is ready.
